# Generated by Django 5.2.4 on 2025-07-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('RAM', 'Memory'), ('SSD', 'Solid State Drive'), ('HDD', 'Hard Disk Drive'), ('PSU', 'Power Supply'), ('MOBO', 'Motherboard'), ('CASE', 'PC Case'), ('FAN', 'Cooling Fan'), ('OTHER', 'Other')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
